### ISSUE TITLE
Question: abilities in other framework

### ISSUE THREAD

**Issue by karlguillotte** [minutebase/ember-can#10]
Hi, 

I am a fan of your addon and I have been using it in some Ember projects. I am interested to know if your addon has been ported to React or if you are aware of other similar project in other framework. I did some research and I did not find anything. 

Thanks in advance

**Comment by rlivsey** [comment]
Hi, sorry I've been away and only just got back.

I'm not aware of a similar library for other JS frameworks. I got ideas from [cancan](https://github.com/ryanb/cancan) and various other authentication libraries but haven't used React / Angular much myself so haven't had the need to investigate there.
