### ISSUE TITLE
Using can in a glimmer component getter blows up dependencies

### ISSUE THREAD

**Issue by makepanic** [minutebase/ember-can#109]
Hi,
I'm in the progress of porting our components to octane and it seems like using can creates a huge list of dependencies.

without can call:

![20200106-110120](https://user-images.githubusercontent.com/1205444/71811822-ee90df00-3075-11ea-8fdb-fc3dbbccf1a2.png)

with can call:

![20200106-110152](https://user-images.githubusercontent.com/1205444/71812008-6232ec00-3076-11ea-91e8-f25cc6d2ee72.png)

It seems like it's somehow adding dependencies to all component properties :thinking: 
I'll try to debug this further.

Seems like this isn't caused by the model passed to the `can` call or its ability implementation.

It also is unrelated to the `parse` implementation in the can service, so it's most likely caused by [`valueFor`](https://github.com/minutebase/ember-can/blob/master/addon/services/can.js#L54) in the service.

Removing code from the method, it seems like both `abilityFor` and `getAbility` won't increase the dependency list that much.

After commenting the [`run(() => ability.destroy());`](https://github.com/minutebase/ember-can/blob/master/addon/services/can.js#L58) the dependency list looked ok again. Maybe it's an upstream issue.

So either we remove the runloop destroy call or fix the runloop creating tons of dependencies here.

**Comment by makepanic** [comment]
It seems like unwrapping `ability.destroy()` from the run call works fine and all tests pass locally.

@Exelord would you be ok with removing the wrapping run call when destroying?

from discord:

> > is it expected that running in a runloop creates a huge amount of dependencies for autotracking?

> run() runs everything in the runloop synchronously, so if you have things scheduled that will cause updates, yes
> By contrast, if you schedule into say actions normally, that will schedule it to run in the next runloop (usually, especially during render)

**Comment by Exelord** [comment]
Hey! Thanks for debugging this. I'm not in context now, why we have the run loop there. From what I remember out tests suit checks things very well. If it works without it, it probably fine to test it first in real apps :)

**Comment by makepanic** [comment]
I've already started using https://github.com/minutebase/ember-can/pull/110 in our app and everything is working well.
