### ISSUE TITLE
Update doc for testing

### ISSUE THREAD

**Issue by david-ratier** [minutebase/ember-can#115]
The doc seems to be outdated regarding testing, also there's not a lot of information.

Right now it's indicated to use `needs: ['helper:can', 'ability:foo']` whereas it seems like in the blueprints a lookup is used.

**Comment by Gorzas** [comment]
@david-ratier Do you have any suggestion about what to show in their place? Could it fit an example of unit test using `ember-can` with [stubs](https://guides.emberjs.com/release/testing/unit-testing-basics/#toc_stubs)?

**Comment by Gorzas** [comment]
After looking through the documentation, in the last versions of Ember using services works the same for Unit and Integration tests. Broader examples are available in the offical EmberJS guides: https://guides.emberjs.com/release/testing/testing-components/#toc_stubbing-services

**Comment by Gorzas** [comment]
Can this issue be closed? 🤔
