### ISSUE TITLE
Stuck at 1.1.1

### ISSUE THREAD

**Issue by betocantu93** [minutebase/ember-can#117]
Hello, we got stuck at 1.1.1 because `abilityFor` returns a new created object every time i.e. Ability.create({}) as thus reopening or metaprogramming got broken for us.

We use defineProperty heavily to create on flight dynamic computeds props on our abilities per model, this is a weird use case, but we basically exported rails `can can can` gem abilities to the frontend and reopen the registered abilities to have the exact same permissions as the backend, per user per role in a totally dynamic fashion

This is a snippet of the kind of dynamism we had working on 1.1.1, just for demo.
 
```ts
['some-model'].forEach(modelName => {

  ['index', 'update'].forEach(actionName => {

     let ability = this.can.abilityFor(modelName);

     //... more code

     let canProp = `_can_auto_${actionName}`; 
     let cannotProp = `_cannot_auto_${actionName}`;

     defineProperty(ability, camelize(`can_{actionName}`), 
       computed(canProp, cannotProp, function() 
        {
          return this.get(canProp) && !this.get(cannotProp)
        });
     })

    //... more code
})
```

What would be a recommended refactor? should I just go back to `owner.lookup` instead of `owner.factoryFor` for `abilityFor` method (as of 1.1.1)? or an `get(owner).unregister`, `register` approach, or any other idea? 

Thanks for the time

**Comment by Exelord** [comment]
Ability is not a singleton and should not be treated like it. That was a bug in the past that allow sharing one instance of ability between many objects which in result leads to model and custom params overrides and incorrectly resolved permissions.

I think you could just move that logic into the ability constructor. If you need to do it in many places, create a base class for them which defines these props. Do you think that would work? :)

**Comment by betocantu93** [comment]
Hmm, these props are totally dynamic coming from an endpoint, per ability type, so in order to do that (inside the constructor, or the creation process) I would need to save these props somewhere, perhaps the `can` service and basically add these props in every .create({}) 

```ts
Ability.create({
...this.configFor(modelName)
})
```
What do you think?

**Comment by Exelord** [comment]
What I mean is to get this config inside of Ability constructor:

```
class Project extends Ability {
  @service session;

  constructor() {
    super();

    this.session.abilities['project']
    // ...define the props
  }
}
```

You cannot assume that the only place abilities are created is your function. Abilities should be isolated and contain any information they need to be able to construct the object.

So I guess you should keep the config somewhere and inject it into abilities so that they can use it during construction.

There is also another option (I think so). You can try to create an Ability class dynamically and register it on demand. Its a meta-programming (depends from your opinions about it).

**Comment by betocantu93** [comment]
Both good options, @Exelord thanks for the follow-up, the last characteristic is that we also do have some hardcoded frontend props, so these dynamic classes would need to extend the hardcoded ones.

```ts
//abilities/project.js
export default class Project extends Ability {
  get canIndex() {
    //some frontend specific validation
      return window.onLine && this.model.role == "admin"
  }
}
//services/session.js
export default class SessionService extends ESASession {
  augmentAbilities() {
     //some meta programming for all ability types
     abilityTypes.forEach(abilityType => {
      //...stuff
      let CurrAbilityKlass = getOwner(this).factoryFor(`ability:${abilityType}`).class;
      let ExtendedAbilityKlass = CurrAbilityKlass.extend(someDynamicProps);
      getOwner(this).unregister(`ability:${abilityType}`)
      getOwner(this).register(`ability:${abilityType}`, ExtendedAbilityKlass)
    })
  }
}
```

Looks good?

**Comment by betocantu93** [comment]
Although this might at some point cross-pollute in a worst case scenario, perhaps the factory should instead be done via literally module lookup, literally require.entries, to be sure we're always extending from the hardcoded one

**Comment by Exelord** [comment]
Im really not sure if you should follow this mete programming solution. I was dealing many times with dynamic abilities and all I needed was just the first solution with a custom constructor.

Registering and deregistering is very hacky :/

**Comment by betocantu93** [comment]
you're  right, i'll follow your advice, thanks!
