### ISSUE TITLE
Explicitly passed ability and property name

### ISSUE THREAD

**Issue by far-fetched** [minutebase/ember-can#119]
Hello,
I really appreciate entire addon, how it structures rights / permissions, and how it delegates responsibility.
But regarding 'can' helper and how it parses string:
I have a strong feeling that for some developers it might be a bit problematic and confusing using string with current approach. E.g. 

`abilities/group.js`

`export default Ability.extend({
   rename: computed('......')
})`

and I want to find all occurrences can / cannot helper  with 'rename' property. So naturally I am looking for string: `rename group`. Results can be from whole projects including: translations, comments etc.
Going further... I found all occurrences and I had modified them. Still I am not sure that one developer didn't make mistake and for example use somewhere like:
`can "rename for group"` 
or
`can "rename to group"`
So it leads me to feeling that I should just look up for string "rename", but of course it is impossible...

So my proposal would be make this string more precise, e.g. add possibility to use it like:

`can "group.canRename"`

Now I can easily find all occurrences in all templates.
I checked current implementation of 'parse' string, in 'can' helper, and adding this feature would be relatively easy... sth like:

`if (string.hasDot) {
   return { ability: string.stringBeforeDot, property: string.stringAfterDot };
}`

What is your opinion ? Please express any ideas.

**Comment by Exelord** [comment]
Isn't it whats documented here? https://github.com/minutebase/ember-can#custom-ability-lookup

**Comment by far-fetched** [comment]
Ahh... somehow I just skipped this section. Indeed, that is what I am looking for. Thanks.
