### ISSUE TITLE
Glimmer incompatibility

### ISSUE THREAD

**Issue by cibernox** [minutebase/ember-can#15]
Not sure if this is a bug in glimmer of should be addressed by `ember-can`.

The can helper doesn't work with glimmer because it expects to receive `env` as 4th argument, but it's not being sent: https://github.com/emberjs/ember.js/blob/57f05daa8fc4fd94e3507e4dab2bcbab3e32f699/packages/ember-htmlbars/lib/hooks/invoke-helper.js#L12

**Comment by rlivsey** [comment]
Just released v0.5.0 with support for Ember 1.13
