### ISSUE TITLE
`can` helper error

### ISSUE THREAD

**Issue by natmegs** [minutebase/ember-can#156]
Hello! I have been running into issue that seems to be a race condition related to the use of `addObserver` and `removeObserver` during route transitions away from a route that renders a template that uses the `can` helper.

```
Uncaught (in promise) Error: Attempted to register a destructor with an object that is already destroying or destroyed
    at registerDestructor
    at getOrCreateActiveObserversFor
    at activateObserver
    at Object.addObserver
    at CanHelper._addAbilityObserver
    at CanHelper.compute
```

Currently using latest version `v4.1.0`. I see that in commits since the release, usage of `addObserver`/`removeObserver` have been removed, and if I apply the diff from this commit https://github.com/minutebase/ember-can/commit/a14a0ce8086c1e468471ca7110a23deee7d307a6 to my node modules directly, the problem goes away.

Would it be possible to release a new patch version to make the change from this commit available?

**Comment by Exelord** [comment]
Hi Natalie,

I think we can try it out. 4.2.0 coming 🚀

**Comment by natmegs** [comment]
@Exelord thank you!

**Comment by Exelord** [comment]
Done!
