### ISSUE TITLE
Failed: A helper named 'can' could not be found

### ISSUE THREAD

**Issue by mmahalwy** [minutebase/ember-can#17]
Hey, seems like my ember-cli is not detecting the can.js helper. When doing: 
```
if (can 'view')
  h1 hello
```

I get error:
```
Failed: A helper named 'can' could not be found
```

Currently using ember-cli 0.2.7 & ember 1.13.2

I thought it was a problem with our app, so I scaffolded a new ember app to double check, and still getting the same error. Seems like the helpers are not found? 

When I manipulated the `app/helpers/can.js` to be renamed to `can-can.js` and helper as `can-can` that removed the helper not found but resulted to:

```
Uncaught TypeError: Cannot read property 'extend' of undefined(anonymous function) @ can.js:7mod.state @ loader.js:141tryFinally @ loader.js:21requireModule @ loader.js:139requireFrom @ loader.js:112reify @ loader.js:97mod.state @ loader.js:140tryFinally @ loader.js:21requireModule @ loader.js:139Ember.DefaultResolver.extend._extractDefaultExport @ ember-resolver.js:367resolveOther @ ember-resolver.js:109superWrapper @ ember.debug.js:17428exports.default.EmberObject.default.extend.resolveHelper @ ember.debug.js:4777exports.default.EmberObject.default.extend.resolve @ ember.debug.js:4594resolve @ ember.debug.js:4437resolve @ ember.debug.js:2109Registry.resolve @ ember.debug.js:1715factoryFor @ ember.debug.js:1317instantiate @ ember.debug.js:1375lookup @ ember.debug.js:1273Container.lookup @ ember.debug.js:1208lookupHelper @ ember.debug.js:8191subexpr @ ember.debug.js:8005render @ application.js:134renderHTMLBarsTemplate @ ember.debug.js:8491renderView @ ember.debug.js:8463renderView @ ember.debug.js:35400mixin.Mixin.create.render @ ember.debug.js:35423EmberRenderer_createElement @ ember.debug.js:37468Renderer_renderTree @ ember.debug.js:9140scheduledRenderTree @ ember.debug.js:9216Queue.invoke @ ember.debug.js:878Queue.flush @ ember.debug.js:943DeferredActionQueues.flush @ ember.debug.js:748Backburner.end @ ember.debug.js:173Backburner.run @ ember.debug.js:228Backburner.join @ ember.debug.js:247run.join @ ember.debug.js:15904run.bind @ ember.debug.js:15966jQuery.Callbacks.fire @ jquery.js:3148jQuery.Callbacks.self.fireWith @ jquery.js:3260jQuery.extend.ready @ jquery.js:3472completed @ jquery.js:3503
```

Coming from https://github.com/minutebase/ember-can/blob/master/addon/helpers/can.js#L4

**Comment by blimmer** [comment]
Very strange, I just created a test app and am not experiencing this problem. You can clone it and check it out [here](https://github.com/blimmer/ember-cli-example-app-for-github/tree/ember-can-issue-17).

It seems like it could be some sort of weird dependency issue if it still happens for you in a new project. Maybe try a `nombom` for sanity check?

```
alias nombom='npm cache clear && bower cache clean && rm -rf node_modules bower_components && npm install && bower install'
```

**Comment by rlivsey** [comment]
Hmm weird, it's working for me on the same versions & the tests are passing. 

Looks like you're using Emblem, although that *shouldn't* be a problem.

A `nombom` is a good idea, let me know if that doesn't fix it and I'll dig a little deeper.

**Comment by mmahalwy** [comment]
Okay I will try that and let you know!

**Comment by ghedamat** [comment]
FYI @mmahalwy I did the usual `nombom` and it started working fine :)

**Comment by mmahalwy** [comment]
@ghedamat thanks for the heads up. I decided to go back to this later on in time for now... :(

**Comment by blimmer** [comment]
@mmahalwy I'm going to close this for now since others don't seem to be having this problem. This is simply a matter of housekeeping, so please don't hesitate to open another issue if the problem you're experiencing persists.

**Comment by mmahalwy** [comment]
Thanks @blimmer! I'll definitely come back to this soon :)
