### ISSUE TITLE
After updating 4.2.0 to 5.0.1 "No ability type found for X"

### ISSUE THREAD

**Issue by urbany** [minutebase/ember-can#175]
Hi all, after updating from 4.2.0 to 5.0.1 none of my abilities are found, I have tried to recreate the POST ability example from the README.md and I'm getting the same error.

I tried to debug but I don't know how the factory works, how can I see if the abilities are getting into the registry?

Thanks in advance

ember-source@5.9.0
ember-cli@5.9.0

**Comment by mkszepp** [comment]
@urbany please the latest... it was fixed in v5.0.3+

**Comment by urbany** [comment]
@mkszepp  will try tomorrow, thank you so much for the quick work on this!

**Comment by RobbieTheWagner** [comment]
This has been fixed.
