### ISSUE TITLE
best way to wait for session.user

### ISSUE THREAD

**Issue by shopapps** [minutebase/ember-can#23]
Hi,
I am using ember-siple-auth and am saving the user object into the session, and the session in turn is injected into ember-can  and all works great, except at the very first loading of the app before the session.user has been collected/stored.

Is there a recomended way of forcing ember-can to wait before the session.user has been stored before responding to any ember-can ability checks?

currently my abilities/requesttype.js file looks like this:

    import Ember from 'ember';
    import { Ability } from 'ember-can';
    
    /*
     * ROLES:
     *    admin
     *    agent
     *    fdc
     */
    export default Ability.extend({
      session: Ember.inject.service(),
      canEdit: Ember.computed(function() {
      	var role = this.session.get('user.role');
      	return (role === 'admin' || role === 'fdc');
      }
    });

**Comment by blimmer** [comment]
Could you make the computed property invalidated by the `user.role` value? I'm not super familiar with ember-simple-auth, but I'd think that by default the user will be `null`, so `canEdit` would go from being false to being true if you did this:

```js
import Ember from 'ember';
import { Ability } from 'ember-can';

/*
 * ROLES:
 *    admin
 *    agent
 *    fdc
 */
export default Ability.extend({
  session: Ember.inject.service(),
  canEdit: Ember.computed('user.role', function() {
    var role = this.session.get('user.role');
    return (role === 'admin' || role === 'fdc');
  }
});
```

**Comment by shopapps** [comment]
Hi,  Thanks for the reply.

I tried what you suggested, but the result is still  the same.  I should have pointed out this is only on a fresh request direct to this route (e.g. bookmarked or typed in address), if the user is in a different route and clicks to this route then it all works as expected.

if the user is not logged in, they always get redirected to a login page, so in theory if the user has gotten to the route /requesttypes there will 'eventually' be a session('user.role') entity.

What i am finding is that it takes an extra second or so for session.user to get populated and so when they get to this route directly (i.e. typed in or from a bookmark) the initial ability checks return false and the user does not see the expected "EDIT" button against each item in a list.  if they click to a different route and then come back again then they DO see the EDIT button (because session('user.role') now exists.

It's almost like I need the 'can edit' to be more like a promise or...  hold off rendering the view until the session.user has been inserted (but i do not know how to achieve this).

Thanks again, and any other advise gratefully received!! :)

**Comment by blimmer** [comment]
The crucial difference between what I wrote and what you wrote is the invalidation of the computed property. How are you exposing the edit button? Are you using the `can` helper?

```handlebars
{{#if (can "edit requesttype")}}
  <button {{action "edit"}}>Edit</button>
{{/if}}
```

That should be working. Any sample code/[ember twiddle](http://ember-twiddle.com/) would be helpful in helping you get this figured out.

**Comment by shopapps** [comment]
Hi,
yes I have the template.hbs as:
    
    {{#if (can "edit requesttype")}}
    <button {{action "edit" item}} class="btn btn-success pull-right btn-m10" type="button"><i class="fa fa-pencil"></i> Edit</button>
    {{/if}}
    
I dont think anything is needed in the  controller??  but i do have:  (note the actual edit action bubbles up so is not listed here)
```
import Ember from 'ember';
import { computed } from 'ember-can';
import { CanMixin } from 'ember-can';

var modelName = 'faulttype';
var modelRoute = Ember.String.pluralize(modelName);

export default Ember.Controller.extend(CanMixin, {

	ability: computed.ability(modelName),
 //  canEditItem: Ember.computed.alias('ability', 'canEdit'),
	// canDeleteItem: Ember.computed.alias('ability', 'canEdit'),

	queryParams: ['sortBy', 'sortAscending'],
	sortAscending: true,
	sortBy: 'name',
	sortProperties: Ember.computed('sortBy', function() {
		return [this.get('sortBy')];
	}),
	actions: {
		setSortBy: function(fieldName) {
			this.set('sortBy', fieldName);
			this.toggleProperty('sortAscending');
			console.log('Sort by: ', fieldName,' dir: ', this.get('sortAscending'));
			return false;
		}
	}
});
```
I've never seen ember twiddle before and am not sure how to write the app in ember style (only use ember-cli), but if really needed I could give it a go.  

I don't think its a bug necessarily, I'm just curious as to how others have solved populating a user object before trying to use that user object in ember-can :)

**Comment by shopapps** [comment]
Hi, I couldn't really get an Ember Twiddle up and running properly so what about a re-wording of the question? :)

Is it possible in a controller to get an ability 'observing' something, so it's state can change when what is observed is changed?

something like: 

    ability: computed.ability('user'),
    canEditUser: Ember.computed.alias('ability', 'canEditUsers').observes('session.user'),

so that canEditUser will re-evaluate each time session.user is changed?

then in the controllers template i can have:
```
{{#if canEditUsers}}
	YES
{{else}}
	NO
{{/if}}
```

I have been able to help my issue a little bit by adding into the routes/application.js
```
model: function(params){
		/* try to hold loading everything until the user is loaded */
		return this.session.get('user');
   },
```

then my sessions/custom.js is:
```
import Ember from 'ember';
import DS from 'ember-data';
import Session from 'simple-auth/session';

export default Session.extend({
	user: function() {
		var userId = this.get('secure.userId');
		if (!Ember.isEmpty(userId)) {
			return DS.PromiseObject.create({
	      	//   store:main   service:store store:application
	      	promise: this.container.lookup('store:main').findRecord('user', userId)
	      });
		}
	}.property('secure.userId', 'isAuthenticated')
});
```

**Comment by blimmer** [comment]
This is absolutely possible, and is exactly what Ember computed properties are for.

In your ability, just have the ability observe what you want:

```js
export default Ability.extend({
  session: Ember.inject.service(),
  user:    Ember.computed.reads('session.user'),

  // observe whatever you want in the computed property
  canEditUsers: Ember.computed('user.id', function() {
    return this.get('user.rolesArr').contains('your_role_from_the_server');
  })
});
```

Then, in your controller, just use `Ember.computed.reads` for your ability. I think you're overthinking needing to use an observer and might not understand how computed properties in Ember work. Maybe have a quick look at the [computed property guide](http://guides.emberjs.com/v1.13.0/object-model/computed-properties/).

**Comment by shopapps** [comment]
you're a genius!  

That's exactly what I was looking for. :+1:   I think my lack of understanding of what the iniital param reference in the Ember.computed tripped me up and the trick of placing the user param reading from the session.   

Your solution was exactly what I was looking for many thanks!

**Comment by blimmer** [comment]
You're welcome. Glad you got it sorted out.

**Comment by owenek1** [comment]
I have similar problem but I need use session data of a user in a model like that: 
```javascript
export default  Ember.Route.extend(AuthenticatedRouteMixin,
{
  model: function(){
    return Ember.RSVP.hash({
      company: this.store.find('company',this.get('session.content.currentUser.companyId')),
      industries: this.store.find('industry')
    });
  }
});
}
```
Everything works when you go to that route from different route, but if you will refresh it then I have following error: company.profile Assertion Failed: You may not pass `undefined` as id to the store's find method. 

Does somebody of you can help me with solving it out? How can I wait for session to be set? I am using a custom:session in following way: 
```javascript
export default Session.extend({
    setCurrentUser: function() {
      var accessToken = this.get('secure.access_token');
      var userId = this.get('secure.user_id');
      var _this = this

      if (!Ember.isEmpty(accessToken)) {
          return _this.container.lookup('store:main').find('user', userId).then(function(user) {
          _this.set('content.currentUser', user);
        });
      }
    }.observes('secure.access_token')
});
```

**Comment by owenek1** [comment]
I have similar problem but I need use session data of a user in a model like that: 
```javascript
export default  Ember.Route.extend(AuthenticatedRouteMixin,
{
  model: function(){
    return Ember.RSVP.hash({
      company: this.store.find('company',this.get('session.content.currentUser.companyId')),
      industries: this.store.find('industry')
    });
  }
});
}
```
Everything works when you go to that route from different route, but if you will refresh it then I have following error: company.profile Assertion Failed: You may not pass `undefined` as id to the store's find method. 

Does somebody of you can help me with solving it out? How can I wait for session to be set? I am using a custom:session in following way: 
```javascript
export default Session.extend({
    setCurrentUser: function() {
      var accessToken = this.get('secure.access_token');
      var userId = this.get('secure.user_id');
      var _this = this

      if (!Ember.isEmpty(accessToken)) {
          return _this.container.lookup('store:main').find('user', userId).then(function(user) {
          _this.set('content.currentUser', user);
        });
      }
    }.observes('secure.access_token')
});
```

**Comment by shopapps** [comment]
what does your session initialiser file look like?


mine looks like:

in /initliazers/session-store.js

export function initialize(container, application) {
  application.inject('session:custom', '_store', 'service:store'); 
}

export default {
  name: 'session-store',
  initialize: initialize,
  after:['ember-data']
};

the after: [‘ember-data’] I think is important,

for completeness my sessions/custom.js file looks like  (note:  service:store is the new Ember > 1.13 way to lookup the store):

import Ember from 'ember';
import DS from 'ember-data';
import Session from 'simple-auth/session';

export default Session.extend({
	user: function() {
		var _parent = this;
		var userId 	= this.get('secure.userId');
		if (!Ember.isEmpty(userId)) {
			return DS.PromiseObject.create({
	      	promise: _parent.container.lookup('service:store').findRecord('user', userId)
	      });
		}
	}.property('secure.userId', 'isAuthenticated')
});


Whenever my models (via a route.js file) are referencing something that should be stored in the session i use fro example:

this.session.get('user.id’)

which is different but may well be just the same as you method of:
> this.get('session.content.currentUser.companyId')

It may be irrelevant, however when you are setting 
> _this.set('content.currentUser', user);
does the ‘content’ param definitely exist?  you could try just:
> _this.set('currentUser', user);
and later do...
> this.session.get('currentUser.companyId')

 



 

Paul Robbins | Director 

DDI:   +44(0) 0118 384 2197 / 08000 124 406
Mob:  +44 (0) 79 30 40 38 40
Email: paul@shopapps.co.uk <mailto:paul@shopapps.co.uk>
ShopApps ltd. Foss Cottage, Soke Road, Silchester, Reading, RG7 2NS.

**Comment by owenek1** [comment]
Thank you for your answer @shopapps. I have made it exactly like you but I am still not able to read data from session in a model, in other places like templates or controller I am able to read. My model for user's profile looks like that: 

```javascript
import Ember from 'ember';
import AuthenticatedRouteMixin from 'simple-auth/mixins/authenticated-route-mixin';

export default Ember.Route.extend(AuthenticatedRouteMixin, {
	model: function() {
	    return Ember.RSVP.hash({
				industries: this.store.find('industry'),
				industryroles: this.store.find('industryrole'),
				company: this.store.find('company',this.session.get('user.companyId'))
		});
	},
	setupController: function(controller, model) {
      controller.set('industries', model.industries);
      controller.set('industryroles', model.industryroles);
      controller.set('company', model.company);
  }
});
```

So with the company model I want to get company that is assigned to the current user. But I am still getting: 
![selection_062](https://cloud.githubusercontent.com/assets/5931978/9378154/86a651a2-471f-11e5-9a74-4d6fe3d47546.png)

As you can see the model in profile route does not wait until users promise is finished. Do you know what am I doing wrong here ?

**Comment by shopapps** [comment]
well, it looks like you are sending an ID with the find company call.  maybe you could try a findAll for the industry and industryrole calls?

**Comment by owenek1** [comment]
yest that is true that I am sending and the user ID with the find company call. So what do you think would be the correct way of getting the company that is assigned to the user. As I understand I should not use in the model informations that are kept with session. Am I right  ?
