### ISSUE TITLE
How to use in a Controller

### ISSUE THREAD

**Issue by shopapps** [minutebase/ember-can#28]
I am following (I believe) your examples but cannot get the output to work as expected, so maybe someone can point out where I'm going wrong:  :)

two scenarios for outputting info in my template:  (template.hbs)

```
{{#if canSendRequests}}
   Can Send method A <br>
{{else}}
   Cannot Send method A<br>
{{/if}}
{{#if (can "send requests")}}
   Can Send method B<br>
{{else}}
   Cannot Send method B<br>
{{/if}}
```

Method A is trying to use a calculated variable taken from the controller, where as Method B is using a template helper method.  For me Method A is not working  (always returns true)

the above produces (for two different users) the following:
1)  An Admin User (who **_should**_ be able to Send)

```
Can Send method A     <-- Correct
Can Send method B     <-- Correct
```

2) Another User (who **_cannot**_ send)

```
Can Send method A     <-- NOT Correct
Cannot Send method B    <-- Correct
```

This is my controller (trimmed down a lot) :  (controller.js)

```
import Ember from 'ember';
import { computed } from 'ember-can';

export default Ember.Controller.extend({
    ability:              computed.ability('requests', 'model'),
    canSendRequests:      Ember.computed.reads('ability', 'canSend'),
});
```

my abilities/requests.js file I assume is correct as the helper version is working as expected, however snippets of this file are:

```
isService: function() {
    var role = this.get('user.role');
    return (role === 'fdc' || role === 'admin' || role === 'super');
 },
canSend: Ember.computed('user.role',function() {
    return this.isService();
 }),
```

Ember version  1.13.10
Ember Can ver:  0.7.0

Can anyone point me in the right direction of where I'm going wrong?  - thanks

**Comment by Exelord** [comment]
In controller or component use `can` service with `can` `cannot` and `build` method to build your own computeds when needed as needed. More examples are coming to the readme.
