### ISSUE TITLE
Remove deprecated use of this.container in favor of getOwner

### ISSUE THREAD

**Issue by mydea** [minutebase/ember-can#35]
On Ember 2.3 a deprecation warning is thrown:
http://emberjs.com/deprecations/v2.x/#toc_injected-container-access

I tried to fix it myself, but it threw a lot of `Attempting to lookup an injected property on an object without a container, ensure that the object was instantiated via a container.` errors in the tests.

**Comment by rlivsey** [comment]
Thanks, I somehow forgot I hadn't updated this project yet.

I'll try and find some time in the next few days, but if you want to take a stab yourself we basically need to:

* [ ] add `ember-getowner-polyfill` to dependencies (not devDependencies)
* [ ] import and use `getOwner` anywhere we're currently getting the container:

Eg [here](https://github.com/minutebase/ember-can/blob/59362175e3fd8393487288deae2edd473a0a2b53/addon/services/can.js#L11) we'd want to change this:

```javascript
const ability = this.container.lookup("ability:"+names.abilityName);
```

To:

```javascript
// import getOwner at the top of the file
import getOwner from 'ember-getowner-polyfill';

// replace this.container with getOwner(this)
const ability = getOwner(this).lookup("ability:"+names.abilityName);
```

Doing that everywhere we currently refer to the container should then keep all the tests passing & get rid of the warnings.

**Comment by mydea** [comment]
I tried that:

https://github.com/mydea/ember-can

but I still get the error message mentioned above. Maybe I missed something, somewhere?

**Comment by rlivsey** [comment]
@mydea hmm that certainly looks like it should work, I'll take a closer look this evening and see if I can figure out what's wrong

Thanks

**Comment by Exelord** [comment]
+1

**Comment by mileszim** [comment]
@mydea using your fork I am no longer getting those deprecation warnings. @rlivsey / @mydea do you think you can get a pull request merged in this week?

**Comment by mydea** [comment]
Yeah, I got rid of the deprecation warnings, but the tests fail, and I don't really know why.

**Comment by mileszim** [comment]
@mydea I submitted a PR with update code all around. Should solve this issue: https://github.com/minutebase/ember-can/pull/36

**Comment by ryanlabouve** [comment]
This seems to be fixed via https://github.com/minutebase/ember-can/commit/65873fd79996fdf5833f15c167fdb959045a4066

Is it possible to close this issue?
