### ISSUE TITLE
Implementing for routes

### ISSUE THREAD

**Issue by ssulistyo** [minutebase/ember-can#37]
You gave this example for checking access to a route:

`import Ember from 'ember';
import { CanMixin } from 'ember-can';

export default Ember.Route.extend(CanMixin, {
  beforeModel: function() {
    if (!this.can('write post')) {
      this.transitionTo('index');
    }
  }
});`

This works in general when navigating to the route, however we have seen some undesired effects when deeplinking to that route or doing a browser page reload. At this point the can evaluation does not seem to work yet and it always triggers the transitionTo() first (meaning you have to go through the navigation again to reach the route

**Comment by blimmer** [comment]
`beforeModel` should fire on every transition into the route whether direct accessing the route or navigating there through. However, it's possible you're mixing in `CanMixin` into the wrong place in the route hierarchy. Can you give us a high level view of where in the routing structure you're mixing this in?

**Comment by ssulistyo** [comment]
We fixed this now in our implementation. Was related to how we handle our user session data and in some situations, the relevant data was not yet available for ember-can to check.

Checks are now in afterModel
