### ISSUE TITLE
Introduction to ember-can on Global Ember Meetup

### ISSUE THREAD

**Issue by taras** [minutebase/ember-can#40]
For some reason, I feel like I already asked about this but I can't see it anywhere.

Would someone from this project be interested in giving an "Introduction to ember-can" on Global Ember Meetup?

An "Introduction to <addon>" talk has the following format
- Why was it created?
- What problem is it trying to solve?
- How do people use it? 
- What should people be aware of?

Would you be interested in giving this talk on April 30th or June 11th?

**Comment by Exelord** [comment]
case overdue :/

**Comment by taras** [comment]
yep yep :)
