### ISSUE TITLE
Attempting to register an unknown factory

### ISSUE THREAD

**Issue by Asherlc** [minutebase/ember-can#45]
Whenever I try to `needs` an ability, I get the following error:
`Attempting to register an unknown factory:`ability:sample-submission``

There's definitely `app/abilities/sample-submission.js` file. What could be causing this?

**Comment by blimmer** [comment]
Is this line in `tests/helpers/resolver.js`?

```javascript
resolver.pluralizedTypes.ability = 'abilities';
```

If not, make sure you followed the [README](https://github.com/minutebase/ember-can#testing) and ran `ember install ember-can` or run `ember g ember-can` now.
