### ISSUE TITLE
Which version of ember to use

### ISSUE THREAD

**Issue by knownasilya** [minutebase/ember-can#5]
You mention that it doesn't work with 1.8, but does it work with 1.9?

**Comment by rlivsey** [comment]
1.9+ should be fine yeah, it's just 1.8 and below which it doesn't work with (which at the time was the current released version of Ember).

**Comment by knownasilya** [comment]
What about 1.8.1?

**Comment by rlivsey** [comment]
It uses the new streams stuff which came in 1.9, so won't work in any of the 1.8.x releases.

It wouldn't be too difficult to get it to work in 1.8.x by changing the way helper bindings to work with non-stream bindings - but I don't personally have the need & it's probably less work to upgrade an app to 1.9+ :grinning:

**Comment by knownasilya** [comment]
>it's probably less work to upgrade an app to 1.9+

I'm having little luck upgrading from 1.8.1 to 1.9.1, getting the following error:

```
Uncaught Error: Unknown template object: function
```

Followed the blog post's instructions.

**Comment by rlivsey** [comment]
IIRC there's an issue where you need to set the htmlbars feature flag in `config/environment.js` for it to work:

```
EmberENV: {
  FEATURES: {
    'ember-htmlbars': true
  }
}
```

**Comment by knownasilya** [comment]
Hum, now I get:

```
WARNING: FEATURE["ember-htmlbars"] is set as enabled, but FEATURE flags are only available in canary builds.
```

**Comment by recipher** [comment]
I think you have to ignore that warning for now (but make sure you enable the flag).

—
Johnny H
07971 880871

**Comment by knownasilya** [comment]
For me it was ember-notify, I upgraded it and everything just worked. No feature flag necessary.

**Comment by rlivsey** [comment]
Glad you got it working. Sorry for the misdirection regarding the feature flag, my memory is hazy!
