### ISSUE TITLE
Question about mutable models

### ISSUE THREAD

**Issue by lancedikson** [minutebase/ember-can#54]
Hey guys! I have a question about models mutability. What if I use this template:

```
import Ember from 'ember';
import { Ability } from 'ember-can';

export default Ability.extend({
  canWrite: Ember.computed('user.isAdmin', function() {
    return this.get('user.isAdmin');
  })
});
```

And some user takes an Ember extension and changed his/her `isAdmin` property. Will the politics show some secret (hidden) parts of the application? Of course, the backend shouldn't react on some disallowed actions from that user, but is there any possibility to protect the property `isAdmin`?

Thanks for your answer in advance.

**Comment by blimmer** [comment]
You're correct - if a user discovers this property and overwrites it locally, `isAdmin` will return true. As you mentioned, you should make sure that the backend does not respond to these actions. You could try obfuscating this property but, at the end of the day, the code is on the client and a savvy user could overwrite the value.

**Comment by lancedikson** [comment]
Got it, thanks :)
