### ISSUE TITLE
Computed properties + additional attributes

### ISSUE THREAD

**Issue by ctjhoa** [minutebase/ember-can#60]
Hi,

Is there a way to do `computed.ability` with additional attributes. 
For a concrete example, how can you write something like this:
```hbs
{{#if (can "remove member from project" project member=member)}}
  ...
{{/if}}
```
using `computed.ability`.

Features exist independently but I cannot find documentation where both are used at the same time.

Thanks

**Comment by Exelord** [comment]
Please do not use `computed.ability`. Instead you can build your own computed property for whatever case you need using `can` service :)
