### ISSUE TITLE
Parent component is destroyed: Cannot read property 'removeObserver' of undefined

### ISSUE THREAD

**Issue by manuel-reil** [minutebase/ember-can#61]
I use the **can helper** in a component template. On click an action bubbles up to the controller, that filters and destroys the component. 

Then the following error is logged to console:

```
TypeError: Cannot read property 'removeObserver' of undefined
    at Class.destroy (can.js:33)
```

**Potential fix:**

Check in `addon/helpers/can.js` if `this._ability` exists:

```
if (this._ability) {
  this._ability.removeObserver(this._abilityProp, this, 'recompute');
}
```

This avoids the particular error in my case, but I do not have the Ember knowledge if the can observer is removed in this case somehow automatically. Typically, *automatically* does not exist...

**Comment by manuel-reil** [comment]
This happens when the can helper is used inside nested `{{#if}}` in a template. Maybe it is not possible to detect the destruction early enough.

**Comment by FilmKnurd** [comment]
Having the same problem. This seems to work pretty well.

**Comment by ErunamoJAZZ** [comment]
I had a very bad day due this issue. I was porting an app from ember 2.8 to 2.16 and this had some weird behavior after fails (more glimmer errors and etc).

I hope someone will merge soon. Thank you guys!

**Comment by blimmer** [comment]
I'm merged and released as 0.8.5.

Myself and @rlivsey don't currently have the time to be very active on this project - is anyone interested in helping maintain this project?

**Comment by acorncom** [comment]
Looks like this issue can be closed now ...  @blimmer I'm likely to start using this add-on in a client project in the next few weeks, what type of help are you looking for here?

**Comment by blimmer** [comment]
Hey @acorncom - thanks for the offer. It seems there's something wrong with the cannot helper as many people have posted about it. There are also some failing tests that could use some touch-up. If you have any time to work on that stuff, I'll happily try to help you get that across the line.
