### ISSUE TITLE
Add readme instructions for using it on an Engine

### ISSUE THREAD

**Issue by esbanarango** [minutebase/ember-can#63]

**Comment by blimmer** [comment]
This project definitely needs help with maintenance. If you have time to put together a PR with this documentation, it would be much appreciated.

**Comment by esbanarango** [comment]
Definitely! I'll add this specific instructions.

**Comment by adambedford** [comment]
@esbanarango Were you able to put together any instructions for this? I'm diving into engines and I'd love some guidance on how to access abilities / `can` helper from within an engine

**Comment by esbanarango** [comment]
@adambedford I'll create the PR with those instructions today! 👍
