### ISSUE TITLE
ember-can v0.8.4 build displays failing

### ISSUE THREAD

**Issue by dianacheung** [minutebase/ember-can#64]
The latest release ember-can v0.8.4 build displays failing, when will that be fixed?

Also on the releases page, only v0.8.2 is tagged "verified" and "latest release".  Does this mean currently v0.8.2 is the latest stable release and v0.8.4 is not?

Thanks in advance.

**Comment by blimmer** [comment]
@dianacheung this project definitely need some help with maintenance. A PR to fix the failing tests would be greatly appreciated if you have time.

The GH releases was an oversight - it's updated now.

**Comment by Exelord** [comment]
Fixed :) - latest v1.0.0 is 💚
