### ISSUE TITLE
How is this different from computed properties? 

### ISSUE THREAD

**Issue by ondrejsevcik** [minutebase/ember-can#80]
Hi guys, how does this addon differ from custom computed properties on model? So instead of having a dedicated file `abilities.js` I can place all my permission checks inside model as `canXYZ` computed property. 

Thank you for explanation.

**Comment by Exelord** [comment]
Yes you can :) But this addon is about structure, helpers and readability. It's very thin, but it does some nice work for you.

Remember, it's bad to keep many responsibilities in one class. That's why we have abilities. To make it simple without models dependency.
