### ISSUE TITLE
Reduce Reliance On Computed Properties

### ISSUE THREAD

**Issue by rtablada** [minutebase/ember-can#83]
When using Ember Can for some recent projects it got me thinking to what a more modern feeling `ember-can` v2 could/would look like.

# Confusing Use of Computed Properties

Right now all `can...` lookups rely on computed properties.
This was really popular at the creation of `ember-can` and was inspired by `@attr` use in can-can but I think that moving to a more functional approach would make things a lot clearer and possibly enable things like #20.

My idea behind this is to make `can...` lookups use functions instead of computed properties like this:

```js
// Before
canEdit: computed('model.isActive', 'session.isAuthenticated', function() {
	return this.get('model.isActive') && this.get('session.isAuthenticated');
})

// After
canEdit(model, props) {
	return model.get('isActive') && this.get('session.isAuthenticated');
}
```

This explicit behavior makes it much clearer how to interact with abilities and reduces the observer stack.
Here in the example I still show the use of having a container aware EmberObject so that things like services can still be injected.

---

I think this would require a v2 release but I think that it could still be done in a backwards compatible way while deprecating computed property ability definitions.

**Comment by Exelord** [comment]
It looks pretty cool but it doesn't cover all our cases :/ We won't be able to track the state required eg in helpers, or change the abilities based on dependents.

**Comment by rtablada** [comment]
🤔yeah I'd need to explore more around how the helper and abilities are being setup. And I'll play around with how to support helper syntax.

Is there a separate ability created for every call to `can`?

**Comment by Exelord** [comment]
Refer to #82

**Comment by rtablada** [comment]
In that case actually a functional approach would solve #82 since a singleton could be used since `model` and `params` would be function arguments instead of instance properties.

But that still raises the question of how to setup observers without leaking required info into templates...

**Comment by Exelord** [comment]
I'm closing this issue. We are not able to achieve the goal with current state of Ember. Feel free to open
