### ISSUE TITLE
The latest release (1.1) doesn't work with any version of Internet Explorer

### ISSUE THREAD

**Issue by calvinlough** [minutebase/ember-can#87]
The use of Object.assign on this line causes IE to blow up:

https://github.com/minutebase/ember-can/blob/0e58e24a3039663d3bce9449687ac0899f0932d2/addon/services/can.js#L27

Of course it works fine if you use a polyfill but we weren't and our app broke in production for all IE users.

**Comment by Exelord** [comment]
Wow. Good catch! 😱
Probably we can just replace it with an ember's polyfill -> https://emberjs.com/api/api/ember/release/functions/@ember%2Fpolyfills/assign

**Comment by Exelord** [comment]
v1.1.1 released :)

**Comment by calvinlough** [comment]
@Exelord Amazing, thank you!
