### ISSUE TITLE
Why are sentences used in the parameters?

### ISSUE THREAD

**Issue by davekaro** [minutebase/ember-can#9]
For example, see https://github.com/minutebase/ember-can#additional-attributes

Why isn't `{{#if-can "remove member from project" project member=member}}` just `{{#if-can "removeMemberFromProject" project member=member}}`?

**Comment by davekaro** [comment]
Sorry this issue is kind of stupid. I just read https://github.com/minutebase/ember-can#looking-up-abilities and understand more now. I'm mostly wondering why we can't just pass the property name directly?

**Comment by rlivsey** [comment]
No worries, not stupid at all! The syntax kind of evolved from some experiments & different ways of looking up / storing the abilities.

I'm completely open to ideas on better / more obvious ways of specifying the ability name and parameters.

**Comment by davekaro** [comment]
Thanks for the feedback. In hindsight, it should have been obvious you've evolved the syntax a bit based on usage. I like the project and will give it a go soon. Will let you know. Thanks!
