### ISSUE TITLE
infinite rendering invalidation detected

### ISSUE THREAD

**Issue by basz** [minutebase/ember-can#95]
With going to ember 3.4 it seems I must use ember-can ^1.1.

However that fails with an `infinite rendering invalidation detected`. This is a strange one.

Firstly I should note I'm using capabilities which return a promise. Templates use the await helper for them to resolve. This used to work with ^0.8.

When I add a console.log in those computed properties I can see they are being called tens of times.

```
  cloneOrder: computed('order.status', function() {
    console.log('cloneOrder');

    return new EmberPromise((resolve, reject) => {
      if (!this.get('can').can('identityUser.isMemberCustomerAdministrator')) {
        return resolve(false);
      }

      if (![orderStatus.ARCHIVED].includes(this.get('order.status'))) {
        return resolve(false);
      }

      this.get('can')
        .can('dossierOrder.belongsToActiveCompanyProfile', null, { order: this.get('order') })
        .then(result => resolve(result));
    });
  }),
```

This is in a template of a row in ember-light-table (2.0.-beta) (shows a dropdown with menu option if any of the abilities resolve to true)

```
{{#if (or
        (await (can 'dossierOrder.cloneOrder' order=row.content))
        (await (can 'dossierOrder.mutateProductionStatus' order=row.content))
        (await (can "dossierOrder.restartProduction" order=row.content))
        (await (can "dossierOrder.useCloudDrive" order=row.content))
      )}}
{{#bs-dropdown closeOnMenuClick=false as |outer-dd|}}
{{#outer-dd.button direction="up" type="link" size='lg' title=(t 'commands.options')}}
      <i class="fa fa-fw fa-cog"></i>
    {{/outer-dd.button}}

    {{#outer-dd.menu as |ddm|}}
      {{#if (await (can 'dossierOrder.cloneOrder' order=row.content))}}
...
```

Whenever I remove the outer `if` the application does not crash (as the properties are not evaluated until the menu is opened). When the dropdown is finally opened the `console.log('cloneOrder');` appears just twice (which is under the 10 for the infinite rendering invalidation error to occures).

So not sure if this is an ember-can an ember-light-table or an other issue. Any tips?

**Comment by basz** [comment]
I solved the immediate issue with the previous version by replacing the template if's with a computed property on the component.

```
  showOptions: computed('row.content', function() {
    return new EmberPromise((resolve, reject) => {
      EmberPromise.all([
        this.get('can').can('dossierOrder.cloneOrder', null, { order: this.get('row.content') }),
        this.get('can').can('dossierOrder.mutateProductionStatus', null, { order: this.get('row.content') }),
        this.get('can').can('dossierOrder.restartProduction', null, { order: this.get('row.content') }),
        this.get('can').can('dossierOrder.useCloudDrive', null, { order: this.get('row.content') }),
      ]).then(function(values){
        resolve(!!values.filter(Boolean).length);
      });
    });
  })
```

However, after upgrading to the 2.0 branch this, seems to fail with `Assertion Failed: Cannot deregister unknown unregistered renderer` as soon as I call a nested ability???

Works; 
```
showOptions: computed('row.content', function() {
    return new EmberPromise((resolve, reject) => {
      resolve(true);
      return;
    });
  })
```
Error...
```
showOptions: computed('row.content', function() {
    return new EmberPromise((resolve, reject) => {
      resolve(true);
      this.get('can').can('dossierOrder.cloneOrder', null, { order: this.get('row.content') });
     return;
    });
  })
```

ps. I have read the async article. And I'm considering switching, but I *think* what I'm doing isn't fundamentally different... (think to be the keyword here, as this is somewhat black magic to me)

**Comment by basz** [comment]
Thought, might this be happening because the `order` (I'll assume the `model` property would suffer the same logic) property on the ability changes when calling an ability? Triggering a rerender for each row in the table? Since I use `computed(`order.status`...` in the abilities?

**Comment by Exelord** [comment]
Could you prepare an Ember Twiddle with not working example? (if you can do it of course) That would speed up debugging.

**Comment by basz** [comment]
Hm. got this far. Can't seem to get ember-can from a feature branch loaded. Can you?

https://ember-twiddle.com/e688458b204a418f8cec161c45d5e63b?openFiles=twiddle.json%2Ctemplates.components.my-component.hbs

**Comment by basz** [comment]
Here one with what I'm trying to do: I'm using 1.1.1

render an options menu if one of the capabilities is allowed. Then inside that render each individual menu option per ability.

https://ember-twiddle.com/e688458b204a418f8cec161c45d5e63b?openFiles=templates.components.my-component.hbs%2Ctemplates.components.my-component.hbs

https://ember-twiddle.com/e688458b204a418f8cec161c45d5e63b?openFiles=templates.components.my-component.hbs%2Ctemplates.components.my-component.hbs

I just noticed that as soon as I added the inner await checks the problems begin. This leads me to try replacing those inner calls also with computed properties on the component.

https://ember-twiddle.com/e688458b204a418f8cec161c45d5e63b?openFiles=templates.components.my-component.hbs%2Ctemplates.components.my-component.hbs

That works. (yeah!) So, either an issue exists with the can helper or mixing template helper and component properties, is not recommended...

Any thoughts or best practices? Thanks anyway...

**Comment by AmilKey** [comment]
@basz any updates on this issue?

**Comment by basz** [comment]
Yes I fixed it in my application.

via these checks in the (row) template 

```
{{#if (await showOptions)}}
  {{#if (await this.ability.cloneOrder)}}`
    ...
  {{#if (await this.ability.mutateProductionStatus)}}`
    ...
  {{#if (await this.ability.useCloudDrive)}}`
    ...
  {{#if (await this.ability.restartProduction)}}`
```

which use the ability defined as

```
  order: alias('row.content'),

  ability: computed('order', 'order.{status,isInProduction}', function() {
    return this.get('can').abilityFor('dossier/order', this.get('order') /*, customProperties */);
  }).volatile(),

  showOptions: computed('order.{status,isInProduction}', function() {
    return new EmberPromise((resolve, reject) => {
      EmberPromise.all([
        this.get('ability.cloneOrder'),
        this.get('ability.mutateProductionStatus'),
        this.get('ability.restartProduction'),
        this.get('ability.useCloudDrive'),
        this.get('ability.transferCadProcessOwner'),
        this.get('ability.transferProductionProcessOwner')
      ]).then(function(values) {
        resolve(!!values.filter(Boolean).length);
      });
    });
  }),
```
Key is that I specifically use the model option of the ability. In addition pls note that I disabled caching via the `.volatile()` modifier.

**Comment by artemgurzhii** [comment]
@basz I've made a fork where you can disable `recompute` call to prevent this error, please take a look at https://github.com/artemgurzhii/ember-can/commit/8cb13dc475f37b1f86e1e78350cd48b72e0bd530
