### ISSUE TITLE
Error in upgrade guide template

### ISSUE THREAD

**Issue by dbendaou** [minutebase/ember-can#96]
Either I didn't understand or there is an error, but the `UPGRADING GUIDE` talk about upgrading from v2.0.0. Or the package is still in v1.1 ..

**Comment by dbendaou** [comment]
I can make a PR if you want

**Comment by Exelord** [comment]
v2 has been not released yet. We are just marking required steps there which will be needed after the release

**Comment by dbendaou** [comment]
Ok my bad then ! You can close :)
